try{
    throw ' a eror'
} catch(err){
    console.log(err);
} finally {
    console.log('it will always run');
}
// if its find eror its run always
// its use for must cases 